# Generated by Django 2.0 on 2020-09-14 10:12

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_icon', models.ImageField(blank=True, default=None, upload_to='head_icon', verbose_name='头像')),
                ('height', models.FloatField(null=True, verbose_name='身高')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=4, verbose_name='性别')),
                ('school', models.CharField(blank=True, max_length=20, null=True, verbose_name='就读或毕业高校')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='用几句话来描述一下你自己吧!')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('write_time', models.DateTimeField(auto_now_add=True, verbose_name='写下这篇博客的时间')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20, verbose_name='博客分类')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True)),
                ('text', models.CharField(max_length=200, verbose_name='评论内容')),
                ('super_comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Comment')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='热度')),
            ],
        ),
        migrations.AddField(
            model_name='blog_type',
            name='hot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Hot'),
        ),
        migrations.AddField(
            model_name='blog',
            name='hot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Hot'),
        ),
        migrations.AddField(
            model_name='blog',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.Blog_Type'),
        ),
    ]
