# Generated by Django 2.0 on 2020-09-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200914_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='super_comment',
        ),
    ]
